FROM php:7.4.6-fpm

ARG UID
EXPOSE $UID

#RUN adduser -u ${UID} --disabled-password --gecos "" appuser
#RUN mkdir /home/appuser/.ssh
#RUN chown -R appuser:appuser /home/appuser/
#RUN echo "StrictHostKeyChecking no" >> /home/appuser/.ssh/config
#RUN echo "export COLUMNS=300" >> /home/appuser/.bashrc
#RUN echo "alias sf=/appdata/www/bin/console" >> /home/appuser/.bashrc

COPY ./php.ini /usr/local/etc/php/php.ini

# Instalamos las dependencias necesarias
RUN apt-get update \
    && apt-get install -y git acl openssl openssh-client wget zip vim librabbitmq-dev libssh-dev \
    && apt-get install -y libpng-dev zlib1g-dev libzip-dev libxml2-dev libicu-dev \
    && docker-php-ext-install intl pdo pdo_mysql zip gd soap bcmath sockets \
    && pecl install xdebug amqp \
    && docker-php-ext-enable --ini-name 05-opcache.ini opcache amqp xdebug \
    && apt-get install -y nodejs
# Instalamos extensiones de PHP
RUN docker-php-ext-install pdo_mysql zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Instalamos composer
RUN curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer
RUN composer self-update
#RUN apt-get update \
#    && apt-get install -y git acl openssl openssh-client wget zip vim librabbitmq-dev libssh-dev \
#    && apt-get install -y libpng-dev zlib1g-dev libzip-dev libxml2-dev libicu-dev \
#    && docker-php-ext-install intl pdo pdo_mysql zip gd soap bcmath sockets \
#    && pecl install xdebug amqp \
#    && docker-php-ext-enable --ini-name 05-opcache.ini opcache amqp xdebug \


#    && apt-get install nodejs -y

RUN mkdir -p /appdata/www

# añadir usuario para la aplicacion laravel


#Deprecated
#USER appuser
#RUN composer global require "hirak/prestissimo:^0.3" --prefer-dist --no-progress --no-suggest --optimize-autoloader --classmap-authoritative \
#	&& composer clear-cache

WORKDIR /appdata/www
